### ISSUE TITLE
Update Repository URL

### ISSUE THREAD

**Issue by cstayyab** [BastienM/aur-walc-appimage#1]
WALC has been moved to separate Organization, Please update the URL to: https://github.com/WAClient/WALC 

If it's not a problem, you may transfer this repository to that organization with full owner access to this repository. It will help people find everything related to WALC under one URL.

Kind Regards

**Comment by BastienM** [comment]
Hi @cstayyab,

Thanks for letting me know.  The latest commit (https://github.com/BastienM/aur-walc-appimage/commit/fe64163ebdf54fced7fd21a62bc3eaaffd17963f) fixes that.

Regarding your ownership suggestion, with the latest notice from the maintainer, WALC is no longer actively developed.
It won't do any good in my opinion. And I have yet to submit this to the AUR as well (and I doubt I would).

If you wish to handle this yourself, I just added a license (unlicense) to allow you to do so :)

Regards
